// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DiceCalculator

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void rolled_clicked(lv_event_t * e);
void sum_clicked(lv_event_t * e);
void d4_clicked(lv_event_t * e);
void d6_clicked(lv_event_t * e);
void d8_clicked(lv_event_t * e);
void d10_clicked(lv_event_t * e);
void d12_clicked(lv_event_t * e);
void d20_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
