// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: DiceCalculator

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_Screen1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollsContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_RollsContainer);
    lv_obj_set_width(ui_RollsContainer, lv_pct(100));
    lv_obj_set_height(ui_RollsContainer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_flow(ui_RollsContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RollsContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_RollsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RolledDice = lv_label_create(ui_RollsContainer);
    lv_obj_set_height(ui_RolledDice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_RolledDice, 1);
    lv_obj_set_align(ui_RolledDice, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_RolledDice, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_RolledDice, "");
    lv_obj_add_flag(ui_RolledDice, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_scroll_dir(ui_RolledDice, LV_DIR_HOR);
    lv_obj_set_style_text_font(ui_RolledDice, &ui_font_DiceFont48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SumContainer = lv_obj_create(ui_RollsContainer);
    lv_obj_remove_style_all(ui_SumContainer);
    lv_obj_set_width(ui_SumContainer, 100);
    lv_obj_set_height(ui_SumContainer, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_SumContainer, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_SumContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SumText = lv_label_create(ui_SumContainer);
    lv_obj_set_width(ui_SumText, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_SumText, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_SumText, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_SumText, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_SumText, "100");
    lv_obj_set_style_text_align(ui_SumText, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SumText, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SumEqualSign = lv_label_create(ui_SumContainer);
    lv_obj_set_width(ui_SumEqualSign, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_SumEqualSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SumEqualSign, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SumEqualSign, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_SumEqualSign, "=");
    lv_obj_set_style_text_font(ui_SumEqualSign, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SumEqualSign, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SumEqualSign, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SumEqualSign, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SumEqualSign, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectionsContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_SelectionsContainer);
    lv_obj_set_width(ui_SelectionsContainer, lv_pct(100));
    lv_obj_set_height(ui_SelectionsContainer, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_SelectionsContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_SelectionsContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SelectionsContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SelectionsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_SelectionsContainer);
    lv_img_set_src(ui_Image3, &ui_img_d4_80h_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 95
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_SelectionsContainer);
    lv_img_set_src(ui_Image4, &ui_img_d6_80h_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 87
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_SelectionsContainer);
    lv_img_set_src(ui_Image5, &ui_img_d8_80h_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 85
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_SelectionsContainer);
    lv_img_set_src(ui_Image6, &ui_img_d10_80h_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 92
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_SelectionsContainer);
    lv_img_set_src(ui_Image7, &ui_img_d12_80h_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 99
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_SelectionsContainer);
    lv_img_set_src(ui_Image8, &ui_img_d20_80h_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_RolledDice, ui_event_RolledDice, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SumContainer, ui_event_SumContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image7, ui_event_Image7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image8, ui_event_Image8, LV_EVENT_ALL, NULL);

}
